export const TAG_OPTIONS = [
  "Luxury",
  "Budget-Friendly",
  "Family-Friendly",
  "Romantic",
  "Business",
  "Casual",
  "Fine Dining",
  "Fast Food",
  "Live Music",
  "Outdoor Seating",
  "Pet-Friendly",
  "Wheelchair Accessible",
  "Vegetarian",
  "Vegan",
  "Halal",
  "Kosher",
  "Gluten-Free",
  "Takeout",
  "Delivery",
  "Reservations",
  "Private Dining",
  "Bar",
  "Rooftop",
  "Waterfront",
  "Historic",
  "Modern",
  "Traditional",
  "Fusion",
  "Street Food",
  "Buffet",
]

export const AMENITY_OPTIONS = [
  "Free WiFi",
  "Parking",
  "Valet Parking",
  "Card Payment",
  "Cash Only",
  "Outdoor Seating",
  "Indoor Seating",
  "Live Music",
  "DJ",
  "Karaoke",
  "TV Screens",
  "Projector",
  "Sound System",
  "Dance Floor",
  "Stage",
  "Private Room",
  "Event Space",
  "Catering",
  "Full Bar",
  "Wine Selection",
  "Cocktail Menu",
  "Happy Hour",
  "Brunch",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Late Night",
  "24 Hours",
  "Drive-Thru",
  "Curbside Pickup",
  "COVID Safe",
  "Contactless Payment",
  "Hand Sanitizer",
  "Temperature Check",
  "Social Distancing",
  "Mask Required",
  "Vaccination Required",
]

export const HIGHLIGHT_OPTIONS = [
  "Nigerian",
  "Ghanaian",
  "South African",
  "Ethiopian",
  "Moroccan",
  "Egyptian",
  "Kenyan",
  "Tanzanian",
  "Authentic",
  "Traditional",
  "Modern",
  "Fusion",
  "Family-Friendly",
  "Romantic",
  "Business",
  "Casual",
  "Fine Dining",
  "Street Food",
  "Vegetarian",
  "Vegan",
  "Halal",
  "Kosher",
  "Gluten-Free",
  "Spicy",
  "Mild",
  "Sweet",
  "Savory",
  "Fresh",
  "Organic",
  "Local Ingredients",
  "Farm-to-Table",
  "Chef's Special",
  "Signature Dish",
  "Award-Winning",
  "Popular",
  "Trending",
  "Hidden Gem",
  "Tourist Favorite",
  "Local Favorite",
  "Best Seller",
]

export const DAYS_OF_WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
]

export const TIME_OPTIONS = [
  "12:00 AM",
  "12:30 AM",
  "1:00 AM",
  "1:30 AM",
  "2:00 AM",
  "2:30 AM",
  "3:00 AM",
  "3:30 AM",
  "4:00 AM",
  "4:30 AM",
  "5:00 AM",
  "5:30 AM",
  "6:00 AM",
  "6:30 AM",
  "7:00 AM",
  "7:30 AM",
  "8:00 AM",
  "8:30 AM",
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
  "8:30 PM",
  "9:00 PM",
  "9:30 PM",
  "10:00 PM",
  "10:30 PM",
  "11:00 PM",
  "11:30 PM",
]

export const PRICE_RANGE_OPTIONS = [
  { value: "$", label: "$ Budget (Under $10)", min: 0, max: 10 },
  { value: "$$", label: "$$ Moderate ($10 - $30)", min: 10, max: 30 },
  { value: "$$$", label: "$$$ Premium ($30 - $60)", min: 30, max: 60 },
  { value: "$$$$", label: "$$$$ Luxury ($60+)", min: 60, max: 999 },
]


